name: Rust

on:
  push: {}
  pull_request: {}

jobs:
  build_test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust:
        - 1.34.0
        - 1.36.0
        - stable
        - beta
        - nightly
        include:
          - rust: nightly
            os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
    - name: Build the crate on minimal version.
      run: |
        cargo build
    - name: Build the crate on 1.36 with features.
      if: matrix.rust != '1.34.0'
      run: |
        # Using `extern crate alloc` is only possible after 1.36
        cargo build --features=alloc,std,grab_spare_slice
    - name: Test on Stable/Beta
      if: matrix.rust != '1.34.0' && matrix.rust != '1.36.0'
      run: |
        cargo test --features=alloc --features=grab_spare_slice --features=rustc_1_40
    - name: Test on Nightly with All Features
      if: matrix.rust == 'nightly'
      run: |
        cargo test --all-features
    # The #[debugger_visualizer] attribute is currently gated behind an unstable feature flag.
    # In order to test the visualizers for the tinyvec crate, they have to be tested on a nightly build.
    - name: Test debugger_visualizer feature on Nightly
      if: |
        matrix.os == 'windows-latest' &&
        matrix.rust == 'nightly'
      run: |
        cargo test --all-features --test debugger_visualizer -- --test-threads=1
